import numpy as np

class orthogonal_chirp_base:
    def __init__(self, fs, f0, f1, M, T, type, method='linear', window=None, win_b=1, optimal=True, max_candidate=100):
        self.fs     = fs                    # Sample frequency
        self.f0     = f0                    # Start frequency
        self.f1     = f1                    # End frequency
        self.M      = M                     # Number of transmitters
        self.T      = T                     # Duration of the chirp

        # ==== Chirp type / direction ====
        if type in ['up', 'u', 1]:          # Up type sub-chirps
            self.type = 'up'
        elif type in ['down', 'd', 2]:      # Down type sub-chirps
            self.type = 'down'
        elif type in ['hybrid', 'h', 3]:    # Hybrid type sub-chirps (up and down)
            self.type = 'hybrid'
        else:
            raise(ValueError(f"Wrong input type : {type}. Available inputs : ['up', 'down', 'hybrid']"))
        
        # ==== Modulation type (WIP) ====
        if method in ['linear', 'lin', 'l']:            # Linear sub-chirps
            self.method = 'linear'
        elif method in ['exponential', 'exp', 'e']:     # Exponential sub-chirps
            self.method = 'exponential'
        elif method in ['hyperbolic', 'hyper', 'h']:    # Hyperbolic sub-chirps
            self.method = 'hyperbolic'
        else:
            raise(ValueError(f"Wrong input method : {method}. Available inputs : ['linear', 'exponential', 'hyperbolic']"))

        # ==== Windowing ====
        if window in ['hamming', 'hanning', 'kaiser']:  # Set window type
            self.window = window
            if window == 'kaiser':                      # If Kaiser, take the beta parameter
                self.window_b = win_b
        elif window is None:                            # If no window
            self.window = None
            self.window_b = None
        else:
            raise(ValueError(f"Wrong input window : {window}. Available inputs : ['hamming', 'hanning', 'kaiser']"))

        # ==== Generate chirp base ====
        # Generate sub-chirps of duration 1/M*T for M sub-bands between f0 and f1
        self.bb_up, self.bb_down = self.generate_chirp_base_block(
            f0=self.f0,
            f1=self.f1,
            fs=self.fs,
            T=self.T,
            M=self.M,
            method=self.method,
            window=self.window,
            b=self.window_b)
        
        # ==== Generate the matrix ====
        # Concatenate M times the sub-chirp base to get the signal of duration T
        self.matrix = self.generate_chirp_matrix(
            chirps_up=self.bb_up,
            chirps_down=self.bb_down,
            fs=self.fs,
            T=self.T,
            M=self.M,
            type=self.type)
        
        # ==== Generate unity height pulses ====
        # Get unity height pulses generated by one random permutation of numbers 0 to M-1
        R = None
        if optimal:
            import sys
            from scipy.special import factorial

            seen = set()                            # Already generated permutations
            R_i = []                                # Permutation sets array

            while len(R_i) < max_candidate:         # Fill permutation array until it reaches max number of candidate permutations 
                p = tuple(np.random.permutation(M)) # Generate a random permutation of M elements
                if p not in seen:                   # If the generated permutation is not already in the array
                    seen.add(p)                     # Append permutation to the seen list
                    R_i.append(p)                   # Append to the permutation list
            R_i = np.array(R_i)
            n_candidates = len(R_i)
            cs_cc = np.zeros(
                (len(R_i), 2),
                dtype=np.float32)                       # Generate max autocorrelation and cross-correlation array

            idx = 0
            
            sys.stdout.write(f"Iterating through {n_candidates} of {factorial(M)} random chirp arrangement candidates:\n")
            sys.stdout.write(f"{idx}/{n_candidates} - {np.float32(100*idx/n_candidates):.2f} %\r")
            sys.stdout.flush()

            for perm in R_i:                            # For each permutation in R_i
                self.uhb = self.unity_height_base(
                    fs=self.fs,
                    T=self.T,
                    M=self.M,
                    R=perm)                             # Generate unity height pulse
                self.bases = self.generate_chirps()     # Generate chirps
                
                m_idx = 0
                n_idx = 0
                max_cs = 0                              # Max autocorrelation value of current permutation
                max_cc = 0                              # Max cross-correlation value of current permutation
                
                from scipy.signal import correlate

                for m in range(M):
                    for n in range(n_idx, M):           # Start at n_idx to prevent recalculations of correlations with previous indices
                        corr = correlate(
                            in1=self.bases[m],
                            in2=self.bases[n],
                            method='fft',
                            mode='full')                # Calculate correlation
                        if m == n:                      # Calculates autocorrelation if indices are the same
                            if np.max(corr) > max_cs:       # If the calculated autocorrelation value is higher than the previous
                                max_cs = np.max(corr)           # Save maximum value for autocorrelation
                        else:                           # Calculates cross-correlation if indices do not match
                            if np.max(corr) > max_cc:       # If the calculated cross-correlation value is higher than the previous
                                max_cc = np.max(corr)           # Save maximum value for cross-correlation
                    n_idx += 1
                    m_idx += 1
                cs_cc[idx][0] = max_cs                  # Save the highest autocorrelation value
                cs_cc[idx][1] = max_cc                  # Save the highest cross-correlation value
                idx += 1

                sys.stdout.write(f"{idx}/{n_candidates} - {np.float32(100*idx/n_candidates):.2f} %\r")
                sys.stdout.flush()
                
            top_candidate = np.argmin(
                cs_cc[:, 0] ** 2 +
                cs_cc[:, 1] ** 2)           # Find the candidate that satisfies Cs^2(a) + Cc^2(a) < Cs^2(b) + Cc^2(b)

            sys.stdout.write(f"\nBest candidate: {top_candidate} --> {R_i[top_candidate]}\n")
            R = R_i[top_candidate]          # Set R to the best candidate
            
        else:
            R = np.random.permutation(M)    # One random permutation of M samples from 0 -> (M - 1)

        # ==== Generate chirps signatures ====
        # Multipliy unity height pulses with the matrix to get the chirps 
        self.uhb = self.unity_height_base(
            fs=self.fs,
            T=self.T,
            M=self.M,
            R=R)                            # Generate the unity height pulses for the permutation R
        self.bases = self.generate_chirps() # Generate the chirps base
        
    def generate_chirp_base_block(self, f0, f1, fs, T, M, method='linear', window=None, b=1):        
        N_CHIRP = int(fs * T / M)                       # Number of sample of one chirp
        t = np.arange(N_CHIRP) / fs                     # Time array
        T_b = T / M                                     # Time duration of one chirp
        chirps_up = np.zeros((M, N_CHIRP))              # Up sub-chirp array
        chirps_down = np.zeros((M, N_CHIRP))            # Down sub-chirp array
        
        for m in range(M):                              # For a set number of transmitters M
            f_s_m = f0 + m * (f1 - f0) / M                  # Start frequency of sub-chirp m
            f_e_m = f_s_m + (f1 - f0) / M                   # End frequency of sub-chirp m
            
            if method in ['linear', 'lin', 'l']:            # If linear, generate linear chirps
                chirps_up[m] = self.linear_chirp(               # Generate linear up chirps
                    t=t,
                    f0=f_s_m,
                    f1=f_e_m,
                    T=T_b)
                chirps_down[m] = self.linear_chirp(             # Generate linear down chirps
                    t=t,
                    f0=f_e_m,
                    f1=f_s_m,
                    T=T_b)
            elif method in ['exponential', 'exp', 'e']:     # If exponential, generate exponential chirps
                chirps_up[m] = self.exponential_chirp(          # Generate exponential up chirps
                    t=t, 
                    f0=f_s_m, 
                    f1=f_e_m,
                    T=T_b)
                chirps_down[m] = self.exponential_chirp(        # Generate exponential down chirps
                    t=t, 
                    f0=f_e_m, 
                    f1=f_s_m, 
                    T=T_b)
            elif method in ['hyperbolic', 'hyper', 'h']:    # If hyperbolic, generate hyperbolic chirps
                chirps_up[m] = self.hyperbolic_chirp(           # Generate hyperbolic up chirps
                    t=t, 
                    f0=f_s_m, 
                    f1=f_e_m, 
                    T=T_b)
                chirps_down[m] = self.hyperbolic_chirp(         # Generate hyperbolic down chirps
                    t=t, 
                    f0=f_e_m, 
                    f1=f_s_m, 
                    T=T_b)

            if window is not None:
                win = None
                if window == 'hanning':
                    win = np.hanning(N_CHIRP)       # Set window to Hanning
                elif window == 'hamming':
                    win = np.hamming(N_CHIRP)       # Set window to Hamming
                elif window == 'kaiser':
                    try:
                        win = np.kaiser(N_CHIRP, b) # Set window to Kaiser
                    except Exception as e:
                        raise(e)
                else:
                    raise(ValueError(f"Wrong input type : {type}. Available inputs : ['hamming', 'hanning', 'kaiser']"))
                
                chirps_up[m] *= win                 # Apply windowing to down chirps
                chirps_down[m] *= win               # Apply windowing to down chirps

        return chirps_up, chirps_down
    
    def linear_chirp(self, t, f0, f1, T):       # Generates an linear chirp
        return np.sin(2 * np.pi * (f0 * t +
            ((f1 - f0) * t ** 2) / (2 * T)))

    def exponential_chirp(self, t, f0, f1, T):  # Generates an exponential chirp
        k = f1 / f0
        return np.sin(2 * np.pi * f0 *
            ((T * ((k ** (t / T)) - 1))
            / np.log(k)))
    
    def hyperbolic_chirp(self, t, f0, f1, T):   # Generates an hyperbolic chirp
        return np.sin(-2 * np.pi *
            ((f0 * f1 * T) / (f1 - f0)) *
            np.log(1 - ((f1 - f0) / (f1 * T) * t)))

    def generate_chirp_matrix(self, chirps_up, chirps_down, fs, T, M, type='hybrid'):
        N = int(fs * T)                         # Total number of samples
        N_CHIRP = int(fs * T / M)               # Number of sample of one chirp
        chirp_matrix = np.zeros((M, N))         # Chirp matrix of M channels by N samples

        if type == 'up':                        # For "up" type sub-chirp base
            for m in range(M):
                for n in range(M):
                    t_c = int(n * N_CHIRP)      # Starting sample of sub-chirp on channel m
                    t_b = int(t_c + N_CHIRP)    # Ending sample of sub-chirp on channel m
                    chirp_matrix[m][t_c:t_b] \
                        = chirps_up[m]          # Append up sub-chirps samples to channel m at m intervals
            return chirp_matrix     

        elif type == 'down':                    # For "down" type sub-chirp base
            for m in range(M):      
                for n in range(M):      
                    t_c = int(n * N_CHIRP)      # Starting sample of sub-chirp on channel m
                    t_b = int(t_c + N_CHIRP)    # Ending sample of sub-chirp on channel m
                    chirp_matrix[m][t_c:t_b] \
                        = chirps_down[m]        # Append down sub-chirps samples to channel m at m intervals
            return chirp_matrix     

        elif type == 'hybrid':                          # For "hybrid" type sub-chirp base
            for m in range(M):      
                for n in range(M):      
                    t_c = int(n * N_CHIRP)              # Starting sample of sub-chirp on channel m
                    t_b = int(t_c + N_CHIRP)            # Ending sample of sub-chirp on channel m
                    if m % 2 == 0:                      # For even rows
                        if n % 2 == 0:                      # For even rows
                            chirp_matrix[m][t_c:t_b] \
                                = chirps_up[m]              # Append up sub-chirp samples to channel m at position n of m
                        else:                           # For odd columns
                            chirp_matrix[m][t_c:t_b] \
                                = chirps_down[m]            # Append down sub-chirp samples to channel m at position n of m
                    else:                               # For odd rows
                        if n % 2 == 0:                      # For even columns
                            chirp_matrix[m][t_c:t_b] \
                                = chirps_down[m]            # Append down sub-chirp samples to channel m at position n of m
                        else:                           # For odd columns
                            chirp_matrix[m][t_c:t_b] \
                                = chirps_up[m]              # Append up sub-chirp samples to channel m at position n of m
            return chirp_matrix
        
        raise(ValueError(f"Wrong input type : {type}. Available inputs : ['up', 'down', 'hybrid']"))

    def unity_height_base(self, fs, T, M, R):
        N = int(fs * T)                         # Total number of samples
        N_CHIRPS = int(fs * T / M)      
        R_i = np.zeros((M, M))                  # Array of all circular shifted sets of R

        for i in range(len(R)):     
            R_i[i] = np.roll(R, i)              # Circular shift of R

        psi = np.zeros((M, M, N))               # Array of unity-height pulses
        for i in range(M):
            for m in range(M):
                t_c = int(R_i[i][m] * N_CHIRPS) # Starting sample of sub-chirp on channel m
                t_b = int(t_c + N_CHIRPS)       # Ending sample of sub-chirp on channel m
                psi[i][m][t_c:t_b] = 1          # Adding ones for range t_c to t_b

        return psi

    def generate_chirps(self):
        N = int(self.fs * self.T)       # Total number of samples
        chirps = np.zeros((self.M, N))  # Array for M constructed chirps
        for m in range(self.M):
            chirp = np.zeros(N)         # Initialize a single chirp
            for n in range(self.M):
                chirp = \
                    chirp + \
                    self.matrix[n] * \
                    self.uhb[m][n]      # Muliply each channel by its unity height pulse and sum each one to make a chirp
            chirps[m] = chirp           # Assign chirp to chirp array
            
        return chirps

    def write(self, path):
        from scipy.io import wavfile

        for m in range(self.M):
            norm_data = self.bases[m] / np.abs(self.bases[m].max())
            wavfile.write(
                filename=f"{path}/chirp_ID_{m}.wav",
                rate=self.fs,
                data=norm_data.astype(np.float32))

    def __str__(self):
        if self.window == 'kaiser':
            return (f"Orthogonal chirp\n\r"
                    f"    Type: {self.type}\n\r"
                    f"    Chirp duration (sec): {self.T}\n\r"
                    f"    Transmitters (M): {self.M}\n\r"
                    f"    Starting frequency: {self.f0}\n\r"
                    f"    Ending frequency: {self.f1}\n\r"
                    f"    Window type: {self.window}\n\r"
                    f"      Beta: {self.window_b}")
        else:
            return (f"Orthogonal chirp\n\r"
                f"    Type: {self.type}\n\r"
                f"    Chirp duration (sec): {self.T}\n\r"
                f"    Transmitters (M): {self.M}\n\r"
                f"    Starting frequency: {self.f0}\n\r"
                f"    Ending frequency: {self.f1}\n\r"
                f"    Window type: {self.window}")

    def __getitem__(self, key):
        return self.bases[key]