import numpy as np
from scipy.io import wavfile
from scipy.special import factorial

class orthogonal_chirp_base:
    def __init__(self, fs, f0, f1, M, T, type, method='linear', window=None, win_b=1):
        self.fs     = fs                    # Sample frequency
        self.f0     = f0                    # Start frequency
        self.f1     = f1                    # End frequency
        self.M      = M                     # Number of transmitters
        self.T      = T                     # Duration of the chirp

        # ==== Chirp type / direction ====
        if type in ['up', 'u', 1]:          # Up type sub-chirps
            self.type = 'up'
        elif type in ['down', 'd', 2]:      # Down type sub-chirps
            self.type = 'down'
        elif type in ['hybrid', 'h', 3]:    # Hybrid type sub-chirps (up and down)
            self.type = 'hybrid'
        else:
            raise(ValueError(f"Wrong input type : {type}. Available inputs : ['up', 'down', 'hybrid']"))
        
        # ==== Chirp function (WIP) ====
        if method in ['linear', 'lin', 'l']:            # Linear sub-chirps
            self.method = 'linear'
        elif method in ['exponential', 'exp', 'e']:     # Exponential sub-chirps
            self.method = 'exponential'
        elif method in ['hyperbolic', 'hyper', 'h']:    # Hyperbolic sub-chirps
            self.method = 'hyperbolic'
        else:
            raise(ValueError(f"Wrong input method : {method}. Available inputs : ['linear', 'exponential', 'hyperbolic']"))

        # ==== Windowing ====
        if window in ['hamming', 'hanning', 'kaiser']:  # Set window type
            self.window = window
            if window == 'kaiser':                      # If Kaiser, take the beta parameter
                self.window_b = win_b
        elif window is None:
            self.window = None
            self.window_b = None
        else:
            raise(ValueError(f"Wrong input window : {window}. Available inputs : ['hamming', 'hanning', 'kaiser']"))

        # ==== Generate chirp base ====
        # Generate sub-chirps of duration 1/M*T for M sub-bands between f0 and f1
        self.bb_up, self.bb_down = self.generate_chirp_base_block(f0=self.f0, f1=self.f1, fs=self.fs, T=self.T, M=self.M, method=self.method, window=self.window, b=self.window_b)
        
        # ==== Generate the matrix ====
        # Concatenate M times the sub-chirp base to get the signal of duration T
        self.matrix = self.generate_chirp_matrix(chirps_up=self.bb_up, chirps_down=self.bb_down, fs=self.fs, T=self.T, M=self.M, type=self.type)
        
        # ==== Generate unity height pulses ====
        # Get unity height pulses generated by one random permutation of numbers 0 to M-1
        self.uhb = self.unity_height_base(fs=self.fs, T=self.T, M=self.M)
        
        # ==== Generate chirps signatures ====
        # Multipliy unity height pulses with the matrix to get the chirps
        self.bases = self.generate_chirps()

    def generate_chirp_base_block(self, f0, f1, fs, T, M, method='linear', window=None, b=1):        
        N_CHIRP = int(fs * T / M)               # Number of sample of one chirp
        t = np.arange(N_CHIRP) / fs             # Time array
        T_b = T / M                             # Time duration of one chirp
        chirps_up = np.zeros((M, N_CHIRP))      # Up sub-chirp array
        chirps_down = np.zeros((M, N_CHIRP))    # Down sub-chirp array
        
        for m in range(M):                      # For a set number of transmitters M
            f_s_m = f0 + m * (f1 - f0) / M      # Start frequency of sub-chirp m
            f_e_m = f_s_m + (f1 - f0) / M       # End frequency of sub-chirp m
            
            if method in ['linear', 'lin', 'l']: 
                chirps_up[m] = self.linear_chirp(t, f_s_m, f_e_m, T_b)
                chirps_down[m] = self.linear_chirp(t, f_e_m, f_s_m, T_b)
            elif method in ['exponential', 'exp', 'e']:
                chirps_up[m] = self.exponential_chirp(t, f_s_m, f_e_m, T_b)
                chirps_down[m] = self.exponential_chirp(t, f_e_m, f_s_m, T_b)
            elif method in ['hyperbolic', 'hyper', 'h']:
                chirps_up[m] = self.hyperbolic_chirp(t, f_s_m, f_e_m, T_b)
                chirps_down[m] = self.hyperbolic_chirp(t, f_e_m, f_s_m, T_b)

            if window is not None:
                win = 0
                if window == 'hanning':
                    win = np.hanning(N_CHIRP)
                elif window == 'hamming':
                    win = np.hamming(N_CHIRP)
                elif window == 'kaiser':
                    try:
                        win = np.kaiser(N_CHIRP, b)
                    except Exception as e:
                        raise(e)
                else:
                    raise(ValueError(f"Wrong input type : {type}. Available inputs : ['hamming', 'hanning', 'kaiser']"))
                
                chirps_up[m] *= win
                chirps_down[m] *= win

        return chirps_up, chirps_down
    
    def linear_chirp(self, t, f0, f1, T):       # Generates a linear chirp
        return np.sin( \
            2 * np.pi * (f0 * t + \
            ((f1 - f0) * t ** 2) / (2 * T)))

    def exponential_chirp(self, t, f0, f1, T):
        k = f1 / f0
        return np.sin( \
            2 * np.pi * f0 * \
            ((T * ((k ** (t / T)) - 1)) \
            / np.log(k)))
    
    def hyperbolic_chirp(self, t, f0, f1, T):
        return np.sin( \
            -2 * np.pi * \
            ((f0 * f1 * T) / (f1 - f0)) * \
            np.log(1 - ((f1 - f0) / (f1 * T) * t)))

    def generate_chirp_matrix(self, chirps_up, chirps_down, fs, T, M, type='hybrid'):
        N = int(fs * T)                 # Total number of samples
        N_CHIRP = int(fs * T / M)       # Number of sample of one chirp
        chirp_matrix = np.zeros((M, N)) # Chirp matrix of M channels by N samples

        if type == 'up':                # For "up" type sub-chirp base
            for m in range(M):
                for n in range(M):
                    t_c = int(n * N_CHIRP)      # Starting sample of sub-chirp on channel m
                    t_b = int(t_c + N_CHIRP)    # Ending sample of sub-chirp on channel m
                    chirp_matrix[m][t_c:t_b] = chirps_up[m] # Append up sub-chirps samples to channel m at m intervals
            return chirp_matrix

        elif type == 'down':        # For "down" type sub-chirp base
            for m in range(M):
                for n in range(M):
                    t_c = int(n * N_CHIRP)      # Starting sample of sub-chirp on channel m
                    t_b = int(t_c + N_CHIRP)    # Ending sample of sub-chirp on channel m
                    chirp_matrix[m][t_c:t_b] = chirps_down[m] # Append down sub-chirps samples to channel m at m intervals
            return chirp_matrix
        
        elif type == 'hybrid':      # For "hybrid" type sub-chirp base
            for m in range(M):
                for n in range(M):
                    t_c = int(n * N_CHIRP)      # Starting sample of sub-chirp on channel m
                    t_b = int(t_c + N_CHIRP)    # Ending sample of sub-chirp on channel m
                    if m % 2 == 0:  # For even rows
                        if n % 2 == 0:  # For even rows
                            chirp_matrix[m][t_c:t_b] = chirps_up[m]     # Append up sub-chirp samples to channel m at position n of m
                        else:           # For odd columns
                            chirp_matrix[m][t_c:t_b] = chirps_down[m]   # Append down sub-chirp samples to channel m at position n of m
                    else:           # For odd rows
                        if n % 2 == 0:  # For even columns
                            chirp_matrix[m][t_c:t_b] = chirps_down[m]   # Append down sub-chirp samples to channel m at position n of m
                        else:           # For odd columns
                            chirp_matrix[m][t_c:t_b] = chirps_up[m]     # Append up sub-chirp samples to channel m at position n of m
            return chirp_matrix
        
        raise(ValueError(f"Wrong input type : {type}. Available inputs : ['up', 'down', 'hybrid']"))

    def unity_height_base(self, fs, T, M):
        N = int(fs * T)                 # Total number of samples
        N_CHIRPS = int(fs * T / M)
        R = np.random.permutation(M)    # One random permutation of M samples from 0 -> (M - 1)
        R_i = np.zeros((M, M))          # Array of all circular shifted sets of R
    
        for i in range(len(R)):
            R_i[i] = np.roll(R, i)      # Circular shift of R

        psi = np.zeros((M, M, N))       # Array of unity-height pulses
        for i in range(M):
            for m in range(M):
                t_c = int(R_i[i][m] * N_CHIRPS)   # Starting sample of sub-chirp on channel m
                t_b = int(t_c + N_CHIRPS)         # Ending sample of sub-chirp on channel m
                psi[i][m][t_c:t_b] = 1              # Adding ones for range t_c to t_b

        return psi

    def generate_chirps(self):
        N = int(self.fs * self.T)                               # Total number of samples
        chirps = np.zeros((self.M, N))                          # Array for M constructed chirps
        for m in range(self.M):
            chirp = np.zeros(N)                                 # Initialize a single chirp
            for n in range(self.M):
                chirp = chirp + self.matrix[n] * self.uhb[m][n] # Muliply each channel by its unity height pulse and sum each one to make a chirp
            chirps[m] = chirp                                   # Assign chirp to chirp array
            
        return chirps

    def write(self, path, format='wav'):
        for m in range(self.M):
            norm_data = self.bases[m] / np.abs(self.bases[m].max())
            wavfile.write(filename=f"{path}/chirp_ID_{m}.wav", rate=self.fs, data=norm_data.astype(np.float32))

    def __str__(self):
        if self.window == 'kaiser':
            return (f"Orthogonal chirp\n\r"
                    f"    Type: {self.type}\n\r"
                    f"    Chirp duration (sec): {self.T}\n\r"
                    f"    Transmitters (M): {self.M}\n\r"
                    f"    Starting frequency: {self.f0}\n\r"
                    f"    Ending frequency: {self.f1}\n\r"
                    f"    Window type: {self.window}\n\r"
                    f"      Beta: {self.window_b}")
        else:
            return (f"Orthogonal chirp\n\r"
                f"    Type: {self.type}\n\r"
                f"    Chirp duration (sec): {self.T}\n\r"
                f"    Transmitters (M): {self.M}\n\r"
                f"    Starting frequency: {self.f0}\n\r"
                f"    Ending frequency: {self.f1}\n\r"
                f"    Window type: {self.window}")

    def __getitem__(self, key):
        return self.bases[key]